ALTER TABLE users ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(128) NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens (user_id);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT,
    user_id BIGINT,
    username VARCHAR(100),
    action VARCHAR(20) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80),
    detail VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_audit_events_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id)
);

CREATE INDEX idx_audit_events_clinic_created ON audit_events (clinic_id, created_at);
CREATE INDEX idx_audit_events_entity ON audit_events (clinic_id, entity_type);

INSERT INTO permissions (code, name, description)
SELECT 'clinic.manage', 'Gestionar clínica', 'Permite editar la identidad y logo de la clínica'
WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE code = 'clinic.manage');

INSERT INTO permissions (code, name, description)
SELECT 'audit.read', 'Ver auditoría', 'Consulta el registro de auditoría de la clínica'
WHERE NOT EXISTS (SELECT 1 FROM permissions WHERE code = 'audit.read');

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN ('clinic.manage', 'audit.read')
WHERE r.code = 'administrador'
  AND r.system_role = TRUE
  AND NOT EXISTS (
      SELECT 1 FROM role_permissions rp
      WHERE rp.role_id = r.id AND rp.permission_id = p.id
  );
