ALTER TABLE clinics ADD COLUMN reminder_hours_before INTEGER NOT NULL DEFAULT 24;
ALTER TABLE clinics ADD COLUMN reminder_message_template VARCHAR(2000);
ALTER TABLE clinics ADD COLUMN reminder_default_country_code VARCHAR(8) NOT NULL DEFAULT '503';

UPDATE clinics
SET reminder_message_template = 'Hola {patientName}, le recordamos su cita el {date} a las {time} en {clinicName}. Confirme su asistencia.'
WHERE reminder_message_template IS NULL;

CREATE TABLE reminder_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL,
    appointment_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    phone_normalized VARCHAR(32) NOT NULL,
    message_body VARCHAR(2000) NOT NULL,
    wa_me_url VARCHAR(512) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    scheduled_for TIMESTAMP WITH TIME ZONE NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_reminder_queue_appointment UNIQUE (appointment_id),
    CONSTRAINT fk_reminder_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id),
    CONSTRAINT fk_reminder_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE CASCADE,
    CONSTRAINT fk_reminder_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
);

CREATE INDEX idx_reminder_queue_clinic_status ON reminder_queue (clinic_id, status, scheduled_for);
