CREATE TABLE periodontogram_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    tooth VARCHAR(8) NOT NULL,
    values_json VARCHAR(4000),
    notes VARCHAR(2000),
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_perio_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id),
    CONSTRAINT fk_perio_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE
);

CREATE INDEX idx_perio_patient ON periodontogram_entries (clinic_id, patient_id, tooth);

CREATE TABLE consent_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    body_html VARCHAR(8000) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_consent_tpl_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id)
);

CREATE INDEX idx_consent_templates_clinic ON consent_templates (clinic_id);

CREATE TABLE patient_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    template_id BIGINT NOT NULL,
    signer_name VARCHAR(160) NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    notes VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_patient_consent_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id),
    CONSTRAINT fk_patient_consent_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
    CONSTRAINT fk_patient_consent_template FOREIGN KEY (template_id) REFERENCES consent_templates (id)
);

CREATE INDEX idx_patient_consents_patient ON patient_consents (clinic_id, patient_id);
