ALTER TABLE clinics ADD COLUMN provider_mode VARCHAR(16) NOT NULL DEFAULT 'MULTI';
ALTER TABLE clinics ADD COLUMN room_mode VARCHAR(16) NOT NULL DEFAULT 'OPTIONAL';
ALTER TABLE clinics ADD COLUMN referrals_inbound_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE clinics ADD COLUMN referrals_outbound_enabled BOOLEAN NOT NULL DEFAULT TRUE;
