CREATE TABLE clinic_receipt_sequences (
    clinic_id BIGINT PRIMARY KEY,
    next_number INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_receipt_seq_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id)
);

CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clinic_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    receipt_number INTEGER NOT NULL,
    paid_at TIMESTAMP WITH TIME ZONE NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    method VARCHAR(20) NOT NULL,
    notes TEXT,
    created_by BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_payments_clinic FOREIGN KEY (clinic_id) REFERENCES clinics (id),
    CONSTRAINT fk_payments_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE,
    CONSTRAINT uk_payments_clinic_receipt UNIQUE (clinic_id, receipt_number)
);

CREATE TABLE payment_allocations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    work_id BIGINT,
    amount NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_payment_alloc_payment FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_alloc_work FOREIGN KEY (work_id) REFERENCES works (id)
);

CREATE INDEX idx_payments_clinic_patient ON payments (clinic_id, patient_id);
CREATE INDEX idx_payments_paid_at ON payments (clinic_id, paid_at);
CREATE INDEX idx_payment_alloc_payment ON payment_allocations (payment_id);
CREATE INDEX idx_payment_alloc_work ON payment_allocations (work_id);
