ALTER TABLE clinics ADD COLUMN provider_mode VARCHAR(16) NOT NULL DEFAULT 'MULTI';
ALTER TABLE clinics ADD COLUMN room_mode VARCHAR(16) NOT NULL DEFAULT 'OPTIONAL';
ALTER TABLE clinics ADD COLUMN referrals_inbound_enabled INTEGER NOT NULL DEFAULT 1;
ALTER TABLE clinics ADD COLUMN referrals_outbound_enabled INTEGER NOT NULL DEFAULT 1;
