import {
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import {
    AGENDA_READ,
    AUDIT_READ,
    CATALOG_READ,
    ODONTOGRAM_READ,
    PATIENTS_READ,
    PRESCRIPTIONS_READ,
    PAYMENTS_READ,
    REFERRALS_READ,
    REPORTS_READ,
    ROLES_MANAGE,
    WORKS_READ,
} from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Inicio',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'patients',
        path: '/pacientes',
        title: 'Pacientes',
        translateKey: 'nav.patients',
        icon: 'patients',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [PATIENTS_READ],
        subMenu: [],
    },
    {
        key: 'agenda',
        path: '/agenda',
        title: 'Agenda',
        translateKey: 'nav.agenda',
        icon: 'agenda',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [AGENDA_READ],
        subMenu: [],
    },
    {
        key: 'reminders',
        path: '/recordatorios',
        title: 'Recordatorios',
        translateKey: 'nav.reminders',
        icon: 'reminders',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [AGENDA_READ],
        subMenu: [],
    },
    {
        key: 'odontogram',
        path: '/odontograma',
        title: 'Odontograma',
        translateKey: 'nav.odontogram',
        icon: 'odontogram',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ODONTOGRAM_READ],
        subMenu: [],
    },
    {
        key: 'treatments',
        path: '/tratamientos',
        title: 'Tratamientos',
        translateKey: 'nav.treatments',
        icon: 'treatments',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [CATALOG_READ],
        subMenu: [],
    },
    {
        key: 'works',
        path: '/trabajos',
        title: 'Trabajos',
        translateKey: 'nav.works',
        icon: 'works',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [WORKS_READ],
        subMenu: [],
    },
    {
        key: 'medications',
        path: '/medicamentos',
        title: 'Medicamentos',
        translateKey: 'nav.medications',
        icon: 'medications',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [PRESCRIPTIONS_READ],
        subMenu: [],
    },
    {
        key: 'prescriptionTemplates',
        path: '/plantillas-receta',
        title: 'Plantillas de receta',
        translateKey: 'nav.prescriptionTemplates',
        icon: 'prescriptionTemplates',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [PRESCRIPTIONS_READ],
        subMenu: [],
    },
    {
        key: 'referrals',
        path: '/referencias',
        title: 'Referencias',
        translateKey: 'nav.referrals',
        icon: 'referrals',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [REFERRALS_READ],
        subMenu: [],
    },
    {
        key: 'roles',
        path: '/roles',
        title: 'Roles y permisos',
        translateKey: 'nav.roles',
        icon: 'roles',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ROLES_MANAGE],
        subMenu: [],
    },
    {
        key: 'audit',
        path: '/auditoria',
        title: 'Auditoría',
        translateKey: 'nav.audit',
        icon: 'audit',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [AUDIT_READ],
        subMenu: [],
    },
    {
        key: 'reports',
        path: '/reportes',
        title: 'Reportes',
        translateKey: 'nav.reports',
        icon: 'reports',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [REPORTS_READ],
        subMenu: [],
    },
    {
        key: 'morosos',
        path: '/morosos',
        title: 'Morosos',
        translateKey: 'nav.morosos',
        icon: 'morosos',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [PAYMENTS_READ],
        subMenu: [],
    },
    {
        key: 'inventory',
        path: '/inventario',
        title: 'Inventario',
        translateKey: 'nav.inventory',
        icon: 'inventory',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [CATALOG_READ],
        subMenu: [],
    },
]

export default navigationConfig
