import {
    NAV_ITEM_TYPE_ITEM,
} from '@/constants/navigation.constant'
import {
    AGENDA_READ,
    CATALOG_READ,
    PATIENTS_READ,
    PRESCRIPTIONS_READ,
    REFERRALS_READ,
    REPORTS_READ,
    ROLES_MANAGE,
} from '@/constants/roles.constant'
import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'home',
        path: '/home',
        title: 'Inicio',
        translateKey: 'nav.home',
        icon: 'home',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
    },
    {
        key: 'patients',
        path: '/pacientes',
        title: 'Pacientes',
        translateKey: 'nav.patients',
        icon: 'patients',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [PATIENTS_READ],
        subMenu: [],
    },
    {
        key: 'agenda',
        path: '/agenda',
        title: 'Agenda',
        translateKey: 'nav.agenda',
        icon: 'agenda',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [AGENDA_READ],
        subMenu: [],
    },
    {
        key: 'treatments',
        path: '/tratamientos',
        title: 'Tratamientos',
        translateKey: 'nav.treatments',
        icon: 'treatments',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [CATALOG_READ],
        subMenu: [],
    },
    {
        key: 'medications',
        path: '/medicamentos',
        title: 'Medicamentos',
        translateKey: 'nav.medications',
        icon: 'medications',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [PRESCRIPTIONS_READ],
        subMenu: [],
    },
    {
        key: 'referrals',
        path: '/referencias',
        title: 'Referencias',
        translateKey: 'nav.referrals',
        icon: 'referrals',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [REFERRALS_READ],
        subMenu: [],
    },
    {
        key: 'roles',
        path: '/roles',
        title: 'Roles y permisos',
        translateKey: 'nav.roles',
        icon: 'roles',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ROLES_MANAGE],
        subMenu: [],
    },
    {
        key: 'reports',
        path: '/reportes',
        title: 'Reportes',
        translateKey: 'nav.reports',
        icon: 'reports',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [REPORTS_READ],
        subMenu: [],
    },
]

export default navigationConfig
